baseURL = "https://www.shinze.com"
title = "shinze"
theme = "shinze"
about = "Everything is mine"
defaultcontentlanguage = "fr"

[params]
author = "Gaëtan Ark"
description = "De tout, *entre autres*"
descriptionlong = "**Gaëtan Ark** (parfois appelé *gatan*, [shinze](twitter.com/shinze) ou encore *papa*), vous trouverez ici de tout, entre autres mais surtout le contenu de mes cours à propos des standards du web."
languageCode = "fr"
github = "https://github.com/shinze/shinzedotcom"

# https://gohugo.io/content-management/taxonomies/
[taxonomies]
category = "categories"
tag = "tags"

[Menus]
main = [
  {Name = "Twitter", URL = "https://twitter.com/shinze"},
  {Name = "LinkedIn", URL = "https://www.linkedin.com/in/gaetanark/"}
]

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
lineAnchors = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = false
style = "manni"
tabWidth = 2
