baseURL = "https://www.shinze.com"
defaultContentLanguage = "fr"
languageCode = "fr"
title = "Shinze"
theme = "hyde"
about = "Everything is mine"

[Menus]
  main = [
      {Name = "Twitter", URL = "https://twitter.com/shinze"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/gaetanark/"}
  ]
  [params]
    author = "Gaëtan Ark"
    description = "De tout, entre autres"
    layoutReverse = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    style = "manni"
    tabWidth = 2
